<h1><?php echo $this->__('Job Management')?></h1>

<form action="<?php echo $this->getPostUrl('job/index/save') ?>" id="jobForm" method="post" enctype="multipart/form-data">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Applicant Information')?></h2>
        <ul class="form-list"> 
        		<li>
		      		<label for="applicant_email" class="required"><em>*</em><?php echo $this->__('Email');?></label>
		          <div class="input-box">
		              <input name="applicant_email" id="applicant_email" title="<?php echo $this->__('Email');?>" value="" class="input-text required-entry validate-email" type="text">
		          </div>
		        </li> 
		        <?php
								$newColumns = Mage::getModel('job/columns')->fetchColumns();
								if($newColumns):
						?>  
								<?php foreach($newColumns as $newColumn):?>
											<li>
													<label for="<?php echo $newColumn['fieldName']?>" <?php if($newColumn['required']=='YES'):?>class="required"<?php endif;?>>
														<?php if($newColumn['required']=='YES'):?><em>*</em><?php endif;?>
														<?php echo $this->__($newColumn['colName'])?>
												</label>
													<div class="input-box">
															<input name="<?php echo $newColumn['fieldName']?>" id="<?php echo $newColumn['fieldName']?>" title="<?php echo $this->__($newColumn['colName'])?>" value="" class="input-text <?php if($newColumn['required']=='YES'):?>required-entry<?php endif;?>" type="text">
													</div>
											</li>
								<?php endforeach;?>
						<?php endif;?>
        </ul>
    </div>
    
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Upload')?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name"><?php echo $this->__('Upload')?></label>
                    <div class="input-box">
                        <input type="file" name="filename" id="filename" title="<?php echo $this->__('Upload')?>" value=""/>
                    </div>
                </div>
			</li>
		</ul>
    </div>
    <div class="buttons-set">
        <p class="required">* <?php echo $this->__('Required Fields')?></p>
        <button type="submit" title="<?php echo $this->__('Submit')?>" class="button"><span><span><?php echo $this->__('Submit')?></span></span></button>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var jobForm = new VarienForm('jobForm', true);
//]]>
</script>
