<?php
/*
 * Module : Job Management
 * Powered By
 * Anx Medma
 */
?>

<h1>Job Management</h1>

<form action="<?php echo $this->getPostUrl('job/index/save') ?>" id="jobForm" method="post" enctype="multipart/form-data">
    <div class="fieldset">
        <h2 class="legend">Applicant Information</h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em>Applicant Name</label>
                    <div class="input-box">
                        <input name="applicant_name" id="applicant_name" title="Applicant Name" class="input-text required-entry" type="text">
                    </div>
                </div>
                <div class="field">
                    <label for="email" class="required"><em>*</em>Email</label>
                    <div class="input-box">
                        <input name="applicant_email" id="applicant_email" title="Applicant Email" value="" class="input-text required-entry validate-email" type="text">
                    </div>
                </div>
            </li>
            <li>
                <label for="telephone">Telephone</label>
                <div class="input-box">
                    <input name="applicant_phone" id="applicant_phone" title="Applicant Phone" value="" class="input-text" type="text">
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend">Upload CV</h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="name" class="required"><em>*</em>Upload</label>
                    <div class="input-box">
                        <input type="file" name="filename" id="filename" title="Upload File" value="" class="required-entry" />
                    </div>
                </div>
			</li>
		</ul>
    </div>
    <div class="buttons-set">
        <p class="required">* Required Fields</p>
        <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
    </div>
</form>

<script type="text/javascript">
//<![CDATA[
    var jobForm = new VarienForm('jobForm', true);
//]]>
</script>
