<form action="<?php echo Mage::helper('adminhtml')->getUrl('job/adminhtml_addcolumns/save')?>" method="post"/>
<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey()?>"/>
	<div class="entry-edit">
		<div class="entry-edit-head">
		    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Add new column')?></h4>
		</div>
		<div class="box">
		        <div class="hor-scroll">
				    <table cellspacing="0" class="form-list">
				        <tbody>
							<tr>
								<td class="label"><?php echo $this->__('Column Name')?></span></td>
								<td class="value">
										<input class="input-text" type="text" name="add_col"/>        
								</td>
							</tr>
							<tr>
								<td class="label"><?php echo $this->__('Required')?></span></td>
								<td class="value">
										<select name="requiredCol">
											<option value="0"><?php echo $this->__('Not Required')?></option>
											<option value="1"><?php echo $this->__('Required')?></option>
										</select>        
								</td>
							</tr>
							<tr><td>&nbsp;</td></tr>
							<tr>
								<td class="a-left"><button title="<?php echo $this->__('Save Column')?>" type="submit"><span><span><span><?php echo $this->__('Save Column')?></span></span></span></button></td>
							</tr>
				    	</tbody>
					</table>
		        </div>
		</div>
	</div>
</form>
